export const osuname :Array<{text: string}> = [
  {"text": "Kreee"},
  {"text": "happybigdio"},
  {"text": "He_ksy"},
  {"text": "RainStormsPEA"},
  {"text": "Mochinaga_Yuna"},
  {"text": "YooLi"},
  {"text": "KCINE"},
  {"text": "kuuhaku9"},
  {"text": "bfdgbzfhs"},
  {"text": "4133chen"},
  {"text": "TeioSanae"},
  {"text": "yueyuezi2002"},
  {"text": "[Crz]Ghost"},
  {"text": "Echo_XF"},
  {"text": "zhaishi"},
  {"text": "A179"},
]