name: Type check and test build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare workspace
        run: npm install

      - name: Generate default config file
        run: cp botconfig.example.ts botconfig.ts

      - name: Test build
        run: npx tsc --build --force --verbose --diagnostics --listFiles

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: dist/
          if-no-files-found: error